"""Review-domain schema: pr_review_jobs and pr_review_steps.

Revision ID: 0001
Revises:
Create Date: 2026-10-10 00:00:00.000000

Hand-written, not autogenerated: autogenerate cannot see the ``updated_at``
trigger and does not reliably emit the ``created_at DESC`` expression indexes
(docs/db_models_and_migrations.md §4; .agents/rules/backend.md § Migrations).
Deviations from the docs schema are deliberate and commented inline.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JOB_STATUSES = "'QUEUED','PROCESSING','RETRYING','COMPLETED','FAILED','SUPERSEDED','SKIPPED'"


def upgrade() -> None:
    op.create_table(
        "pr_review_jobs",
        # gen_random_uuid(): builtin since PostgreSQL 13.
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        # Nullable: manual re-runs have no webhook delivery; PostgreSQL permits
        # unlimited NULLs under UNIQUE.
        sa.Column("delivery_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        # DEVIATION from docs/db_models_and_migrations.md §1.1: the docs make
        # this a UUID FK into installations. Tenancy tables are deferred to a
        # later migration, so the forge's numeric installation id is stored
        # directly until that lands.
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_full_name", sa.String(length=255), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        # Nullable only for command-originated jobs (docs §1.1); the CHECK
        # below keeps every webhook-originated row strict.
        sa.Column("head_sha", sa.String(length=40), nullable=True),
        sa.Column("base_sha", sa.String(length=40), nullable=True),
        sa.Column("event_action", sa.String(length=32), nullable=False),
        # D5 (docs/PIPELINE_SPEC.md §7.2, decided 2026-10-10): PR metadata for
        # the review list; all four values arrive in the webhook payload.
        # Empty string allowed: the forge always sends a title on webhook
        # events, and an empty one must not fail the insert.
        sa.Column("pr_title", sa.String(length=255), nullable=False),
        sa.Column("author_login", sa.String(length=255), nullable=True),
        sa.Column("head_ref", sa.String(length=255), nullable=True),
        sa.Column("base_ref", sa.String(length=255), nullable=True),
        sa.Column("author_external_id", sa.String(length=64), nullable=True),
        # Normalised vocabulary, not the forge's (docs §1.1).
        sa.Column("author_association", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="QUEUED"),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="3"),
        # GitHub Check Run id, or GitLab MR note id — same role, one column.
        sa.Column("external_check_id", sa.BigInteger(), nullable=True),
        # No FK to config_snapshots: that table arrives with the configuration
        # migrations; the digest stays for audit only (docs §1.1).
        sa.Column("config_digest", sa.String(length=64), nullable=True),
        # ADDITION to the docs schema: parsed-diff stats written by the worker.
        # Added while 0001 is still editable (docs/db_models_and_migrations.md
        # §6) rather than in a follow-up revision.
        sa.Column("stats", postgresql.JSONB(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        # server_default, not a Python default: claim and reap are raw UPDATE
        # statements that never pass through the ORM (docs §1.1).
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "delivery_id", name="uq_pr_review_jobs_delivery_id"),
        sa.CheckConstraint("provider IN ('github','gitlab')", name="ck_pr_review_jobs_provider"),
        sa.CheckConstraint(f"status IN ({JOB_STATUSES})", name="ck_pr_review_jobs_status"),
        sa.CheckConstraint(
            "retry_count >= 0 AND retry_count <= max_retries",
            name="ck_pr_review_jobs_retry_bounds",
        ),
        sa.CheckConstraint(
            "event_action = 'command' OR (head_sha IS NOT NULL AND base_sha IS NOT NULL)",
            name="ck_pr_review_jobs_sha_present",
        ),
        sa.CheckConstraint(
            "author_association IS NULL OR author_association IN "
            "('OWNER','COLLABORATOR','CONTRIBUTOR','NONE')",
            name="ck_pr_review_jobs_author_association",
        ),
    )

    # Partial indexes: each covers only rows in the relevant state, so the
    # queue indexes stay small no matter how large the audit history grows.
    op.create_index(
        "ix_pr_review_jobs_claim",
        "pr_review_jobs",
        ["next_attempt_at"],
        postgresql_where=sa.text("status IN ('QUEUED','RETRYING')"),
    )
    op.create_index(
        "ix_pr_review_jobs_active_pr",
        "pr_review_jobs",
        ["installation_id", "repo_id", "pr_number"],
        postgresql_where=sa.text("status IN ('QUEUED','RETRYING','PROCESSING')"),
    )
    op.create_index(
        "ix_pr_review_jobs_reaper",
        "pr_review_jobs",
        ["locked_until"],
        postgresql_where=sa.text("status = 'PROCESSING'"),
    )
    # DEVIATION from docs §1.1: the docs index account_id; accounts arrive
    # with the tenancy migration, so the MVP keys per-account fairness on
    # installation_id. There is likewise no ix_pr_review_jobs_account_history:
    # no account_id exists yet.
    op.create_index(
        "ix_pr_review_jobs_inflight",
        "pr_review_jobs",
        ["installation_id"],
        postgresql_where=sa.text("status = 'PROCESSING'"),
    )
    op.create_index(
        "ix_pr_review_jobs_pr_history",
        "pr_review_jobs",
        ["installation_id", "repo_id", "pr_number", sa.text("created_at DESC")],
    )

    op.create_table(
        "pr_review_steps",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("step", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="RUNNING"),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("error_detail", sa.String(length=1000), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["job_id"], ["pr_review_jobs.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("job_id", "attempt", "seq", name="uq_pr_review_steps_job_attempt_seq"),
        sa.CheckConstraint(
            "step IN ('CLAIMED','AUTH','FETCH_DIFF','BUILD_CONTEXT',"
            "'REDACT','GATE','LLM_CALL','POSTPROCESS','POST_FEEDBACK','METER')",
            name="ck_pr_review_steps_step",
        ),
        sa.CheckConstraint(
            "status IN ('RUNNING','OK','FAILED','SKIPPED')",
            name="ck_pr_review_steps_status",
        ),
    )
    op.create_index("ix_pr_review_steps_step_started", "pr_review_steps", ["step", "started_at"])

    # updated_at maintained by trigger, not by ORM onupdate: the claim and
    # reaper paths are raw UPDATE statements that never pass through the ORM
    # (docs/db_models_and_migrations.md §4).
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_pr_review_jobs_updated_at
        BEFORE UPDATE ON pr_review_jobs
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)


def downgrade() -> None:
    # Dependents first; dropping a table drops its own indexes and constraints.
    op.execute("DROP TRIGGER IF EXISTS trg_pr_review_jobs_updated_at ON pr_review_jobs;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    op.drop_table("pr_review_steps")
    op.drop_table("pr_review_jobs")
